version: '3'

services:
    nginx:
        image: nginx:1.22.0-alpine
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./var/log:/var/log/nginx
        depends_on:
            - php-fpm
        ports:
            - "80:80"
            - "443:443"
        networks:
            - marketplace-sylius
    
    db:
        image: mysql
        volumes:
            - db-data-sylius-zartizana:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=nopassword
            - MYSQL_DATABASE=sylius
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=nopassword
        networks:
            - marketplace-sylius
        ports:
            - "33306:3306"
    
    php-fpm:
        build:
            context: ./docker/php-fpm
        depends_on:
            - db
        environment:
            - APP_ENV=prod
            - APP_DEBUG=0
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./docker/php-fpm/whatever.ini:/usr/local/etc/php/conf.d/whatever.ini
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php-fpm/php-cli.ini:/usr/local/etc/php/conf.d/php-cli.ini
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - marketplace-sylius

    node:
        image: "node:14-alpine"
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=${APP_ENV}
        volumes:
            - ./:/home/node/app
        command: >
            sh -c "yarn install
            && yarn build"
        networks:
            - marketplace-sylius

networks:
    marketplace-sylius:

volumes:
    db-data-sylius-zartizana:
