sylius_grid:
    grids:
        sylius_admin_product_variant:
            sorting:
                position: asc
#            fields:
#                marketPlaceVendor:
#                    type: string
#                    label: 'MarketPlaceVendor ID'

    
